### ISSUE TITLE
Simplify Graylog server configuration

### ISSUE THREAD

**Issue by joschi** [etki/docker-graylog#2]
While it's badly (i. e. not at all) documented, it's possible to override Graylog configuration settings with environment variables with the prefix `GRAYLOG2_`.

For example `GRAYLOG2_PASSWORD_SECRET` will override the `password_secret` setting from the configuration file and `GRAYLOG2_MONGODB_URI` will override the `mongodb_uri` setting from the configuration file.

**Comment by etki** [comment]
@joschi updated everything i could, i hope i'll find some more time to simplify long parameters
